config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get '/pages/about', to: 'pages#about'
  get '/pages/portfolio', to: 'pages#portfolio'
  get '/pages/skills', to: 'pages#skills'
  get '/pages/contact', to: 'pages#contact'
  get '/pages/try', to: 'pages#try'


  match '/contacts',     to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "New Contact From My Website",
      :to => "finegoz@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.request = request
    if @contact.deliver
      flash[:notice] = 'Thank you for your message. I will contact you soon!' 
      redirect_to pages_contact_path 
    else
      flash[:error] = 'Cannot send message.' 
      redirect_to pages_contact_path 
      render :new
    end
  end
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div class="container" style="padding-top: 20px">
  <div class="row">
    <div class="col-md-6 col-md-push-3">
      <div class="panel" style="border-radius: 0px; min-height: 300px; border: none">
        <div class="panel-heading text-center" style="background: #4D4D4D; border-radius: 0px">
          <h2 style="color: white">Send Me A Message</h2>
        </div>
        <div class="panel-body">  
          <%= bootstrap_form_for(Contact.new) do |f| %>
            <div class="row">
              <div class="col-md-6">
                <%= f.text_field :name, placeholder: "Enter Email" %>
              </div>
              <div class="col-md-6">
                <%= f.email_field :email, placeholder: "Enter Email" %>
              </div>                
            </div><br> 
            <div class="row">
              <div class="col-md-6"> 
                <%= f.text_area :message, placeholder: "Enter Message Here" %>
              </div>  
            </div><br> 
            <div class="row">
              <div class="col-md-12">             
                <%= f.submit "Send Message" %>
              </div>  
            </div>              
          <% end %>  
        </div>  
      </div>
    </div>
  </div>
</div>      

app/views/layouts/_footer.html.erb
<footer class="footer font hidden-xs hidden-sm" style="background-color: inherit; position: fixed; bottom:0">
  <div class="container">
    <div class="row"> 
      <div class="col-md-12 col-xs-12 col-sm-12 text-center">
        <div class="sm">
          <a href="https://github.com/yogev1"><%= image_tag "github-icon.png", class: "img-responsive" %></a>
          <a href="https://www.linkedin.com/in/yogev-finegoz-b0071095/" ><%= image_tag "LI-icon.png", class: "img-responsive" %></a>
        </div>
      </div>
    </div> 
  </div>     
</footer>

<footer class="footer font hidden-md hidden-lg" style="background-color: inherit; position: fixed; bottom:0; min-height: 30px">
  <div class="container">
    <div class="row"> 
      <div class="col-md-12 col-xs-12 col-sm-12 text-center">
        <div class="sm">
          <a href="https://github.com/yogev1"><%= image_tag "github-icon.png", class: "img-responsive" %></a>
          <a href="https://www.linkedin.com/in/yogev-finegoz-b0071095/" ><%= image_tag "LI-icon.png", class: "img-responsive" %></a>
        </div>
      </div>
    </div> 
  </div>     
</footer>

app/views/layouts/_navbar.html.erb
<input type="checkbox" id="navcheck" role="button" title="menu" style="opacity: 0">
<label for="navcheck" aria-hidden="true" title="menu">
  <span class="burger">
    <span class="bar">
    </span>
  </span>
</label>
<nav id="menu">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12 text-center grow">
      <a href="<%= root_path %>" style="font-size: 350%"><i class="glyphicon glyphicon-thumbs-up"></i></a>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 text-center grow">  
      <a href="/pages/about" style="font-size: 400%">About</a>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 text-center grow">       
      <a href="/pages/portfolio" style="font-size: 400%">Portfolio</a>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 text-center grow">       
      <a href="/pages/skills" style="font-size: 400%">Skills</a>
    </div>
    <div class="col-md-12 col-sm-12 col-xs-12 text-center grow">       
      <a href="/pages/contact" style="font-size: 400%">Contact</a>
    </div>  
  </div>
</nav>










   
    
    
    
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://code.jquery.com/jquery-latest.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Rozha+One" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
  
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
	
  <title>Yogev Fine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body class="bold" style="background-color: ">
  <div id="navbar"><%= render 'layouts/navbar' %>
  </div>
	<%= yield %>
  <div>
  <% if !(params[:controller] == 'pages' && params[:action] == 'index') && !(params[:controller] == 'pages' && params[:action] == 'about') %>
    <%= render 'layouts/footer' %>
  <% end %>
  </div>  
</body>
</html>

app/views/pages/about.html.erb
<div class="container hidden-xs hidden-sm" style="padding-top: 20px"> 
  <div class="row">
    <div class="col-md-12 col-lg-12 text-center" style="padding-bottom: 40px">
      <h1 style="font-size: 600%; font-weight: bold;" id="about" class="about animated">About</h1>
      <p align="center"><span class="hr3"></span></p>
    </div>
  </div>   
</div>
<div class="container font hidden-xs hidden-sm" style="margin-bottom: 50px; margin-top: 50px; color:#F0FFFF">
  <div class="row">  
    <div class="col-md-4 col-lg-4 text-center">
      <p><span class="glyphicon glyphicon-user font-col-light animated rollIn" style="font-size: 1000%"></span></p><br><br>
      <h1 id="head" class="font-col-light"></h1><br>
      <h1 class="font-col-light animated slideInLeft">
        Ambitious Junior engineer with experience in the fields of software engineering, computer networks and cyber security.  
      </h1>
    </div>
    <div class="col-md-4 col-lg-4 text-center">
      <p><span class="glyphicon glyphicon-briefcase font-col-light animated rollIn" style="font-size: 1000%"></span></p><br><br> 
      <h1 id="head" class="font-col-light"></h1><br>
      <h1 class="font-col-light animated slideInUp">
        Goal Oriented individual Seeking a full time position as a Full Stack Engineer.
      </h1>        
    </div>
    <div class="col-md-4 col-lg-4 text-center">
      <p><span class="glyphicon glyphicon-education font-col-light animated rollIn" style="font-size: 1000%"></span></p><br><br>
      <h1 id="head" class="font-col-light"></h1><br>
      <h1 class="font-col-light animated slideInRight">
        Hard working, motivated and enthusiastic about technology and eager to learn and progress.
      </h1>        
    </div>      
  </div>
  <div class="row">
    <div class="col-md-12 col-lg-12 text-center">
      <a class: "drop" href="<%= root_path %>"><%= image_tag("arrow_left.png", size: "400x80") %></a>
      <a class: "drop" href="<%= pages_portfolio_path %>"><%= image_tag("arrow_right.png", size: "400x80") %></a>
    </div>
  </div>   
</div>    


<div class="hidden-md hidden-lg" style="position: absolute; right: 0; left: 0; padding-bottom: 50px; padding-top: 20px">
  <div class="container"> 
    <div class="row">
      <div class="col-sm-10 col-xs-12 text-center" style="margin-top: 50px; padding-bottom: 40px">
        <h1 style="font-size: 300%; font-weight: bold;" id="about" class="font-col-light">About</h1>
        <p align="center"><span class="hr3"></span></p>
      </div>
    </div>   
  </div>
  <div class="container font" style="margin-bottom: 50px">  
    <div class="row">  
      <div class="col-sm-12 col-xs-12 text-center">
        <p><span class="glyphicon glyphicon-user animated rollIn" style="font-size: 1000%; color: #484848"></span></p><br>
        <h1 id="head" style="color: #484848"></h1><br>
          <h1 class="font-col-light animated slideInLeft">
            Ambitious Junior engineer with experience in the fields of software engineering, computer networks and cyber security.  
          </h1><br><br>
      </div>
      <div class="col-sm-12 col-xs-12 text-center">
        <p><span class="glyphicon glyphicon-briefcase font-col-light animated rollIn" style="font-size: 1000%; color: #484848"></span></p><br> 
        <h1 id="head" class="font-col-light"></h1><br>
        <h1 style="color: #484848" class="font-col-light animated slideInUp">
          Goal Oriented individual Seeking a full time position as a Full Stack Engineer.
        </h1><br><br>        
      </div>
      <div class="col-sm-12 col-xs-12 text-center">
        <p><span class="glyphicon glyphicon-education font-col-light animated rollIn" style="font-size: 1000%; color: #484848"></span></p><br><br>
        <h1 id="head" class="font-col-light"></h1><br>
        <h1 style="color: #484848" class="font-col-light animated slideInRight">
          Hard working, motivated and enthusiastic about technology and eager to learn and progress. 
        </h1>        
      </div>      
    </div>
    <div class="row">
      <div class="col-md-12 col-xs-12 col-sm-12 text-center">
        <a class: "drop" href="<%= root_path %>"><%= image_tag("arrow_left.png", size: "300x80") %></a>
        <a class: "drop" href="<%= pages_portfolio_path %>"><%= image_tag("arrow_right.png", size: "300x80") %></a>
      </div>
    </div>  
  </div>    
</div> 

app/views/pages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12 cov nopadding-index" style="background-image: url(<%= asset_path 'photo.jpg' %>); position: absolute; width: 100%; top:0; left:0; bottom:0; height: 100%; zoom: 55%; background-size:cover; background-repeat: no-repeat">
    </div>
    <div class="col-md-6 col-lg-6 col-sm-12 col-xs-12 " style="margin-top: 10%">
      <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 col-sm-push-12 col-md-push-12 col-lg-push-12 text-center hidden-xs">
          <a href="/pages/about"class="btn-outlined btn-theme btn-lg" data-wow-delay="0.7s" style="font-size:400%">About</a>
        </div> 
        <div class="hidden-lg hidden-md hidden-sm text-center col-xs-12" style="margin-top: 400px">
          <a href="/pages/about"class="btn-outlined2 btn-theme btn-lg" data-wow-delay="0.7s" style="font-size:400%">About</a>
        </div>                       
      </div>    
      <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12 hidden-xs col-sm-push-12 text-center" style="margin-top: 50px">  
          <div style="color: black; font-size: 300%" class="element-home"> 
          </div>
        </div> 
        <div class="hidden-lg hidden-md hidden-sm col-xs-12 text-center" style="margin-top: 30px">  
          <div style="color: white; font-size: 300%" class="element-home2"> 
          </div>
        </div>                      
      </div> 
    </div>    
  </div>     
</div>

   

app/views/pages/portfolio.html.erb
<div class="two" style="position: absolute; padding-top: 20px; min-height: 60vw; background-size:cover; width: 100%; right: 0; left: 0"> 
  <div class="container" id="portfolio">
    <div class="row hidden-xs">
      <div class="col-md-12 col-sm-12 col-xs-12 text-center" style="margin-top: 10px; margin-bottom: 50px">
        <h1 style="font-size: 700%; font-weight: bold;" class="font-col-light animated bounceInLeft">Portfolio</h1>
        <p align="center"><span class="hr3 animated flip"></span></p>
      </div>
    </div>
    <div class="row hidden-lg hidden-md hidden-sm">
      <div class="col-md-12 col-sm-12 col-xs-12 text-center" style="margin-top: 60px; margin-bottom: 50px">
        <h1 style="font-size: 700%; font-weight: bold;" class="font-col-light animated bounceInLeft">Portfolio</h1>
        <p align="center"><span class="hr3 animated flip"></span></p>
      </div>
    </div>      
    <div class="row text-center center-block">
      <div class="col-md-2 col-sm-6 col-xs-12" style="margin-bottom: 60px">    
        <div id="cube-buttons">
          <button class="btn1 btn-outlined btn-theme btn-md" style="font-size: 200%">Sports-Meet-App</button> 
          <button class="btn1 btn-outlined btn-theme btn-md" style="font-size: 200%">SocialNet</button> 
          <button class="btn1 btn-outlined btn-theme btn-md" style="font-size: 200%">DMViz</button>
        </div>
      </div>
      <div class="col-md-10 col-md-pull-1">      
        <div class="cube-container" id="demo-cube">
          <div class="cube toFront">      
            <div class="face top" style="background-color: white; opacity: 0.8">
            </div>
            <div class="face front" style="background-color: white; opacity: 0.8">
              <h3 style="margin-top: 10px; font-size: 200%" class="font">Sports Meet-App</h3>
              <div class="row">
                <div class="col-md-11 col-xs-11 col-sm-6 text-center nopadding" style="margin-left: 17px; margin-top: 10%">
                  <div data-toggle="modal" data-target="#mymodal1">
                    <p class="title">Sports Meet-App</p>
                    <h3 class="title2">Click the banner for more details<h3>
                      <%= image_tag("sports2.jpeg", class: "img-responsive", style: "background-size: contain;height: 300px; max-width: 350px") %>
                  </div>
                </div>
                <div class="col-md-1">
                </div>
              </div>           
            </div>
            <div class="face bottom" style="background-color: white; opacity: 0.8">
              <h3 style="margin-top: 10px; font-size: 200%" class="font">SocialNet</h3>
              <div class="row">
                <div class="col-md-11 col-xs-12 col-sm-6 text-center nopadding" style="margin-left: 17px; margin-top: 10%">
                  <div data-toggle="modal" data-target="#mymodal2">
                    <p class="title">SocialNet</p>
                    <h3 class="title2">Click the banner for more details<h3>
                      <%= image_tag("social.png", class: "img-responsive", style: "height: 300px; max-width: 350px") %> 
                  </div>
                </div>
                <div class="col-md-1">
                </div>            
              </div>              
            </div>
            <div class="face left" style="background-color: white; opacity: 0.9">
              <h3 style="margin-top: 10px; font-size: 200%" class="font">CarList</h3>
              <div class="row">
                <div class="col-md-11 col-xs-12 col-sm-6 text-center nopadding" style="margin-left: 17px; margin-top: 10%">
                  <div data-toggle="modal" data-target="#mymodal3">
                    <p class="title">CarList</p>
                    <h3 class="title2">Click the banner for more details<h3>
                      <%= image_tag("car.jpeg", class: "img-responsive", style: "height: 300px; max-width: 350px") %> 
                  </div> 
                </div>           
              </div>
            </div>
            <div class="face right" style="background-color: white; opacity: 0.9">
              <h3 style="margin-top: 10px; font-size: 200%" class="font">D.M.Viz</h3>
              <div class="row">        
                <div class="col-md-11 col-xs-12 col-sm-6 text-center nopadding" style="margin-left: 17px; margin-top: 10%">
                  <div data-toggle="modal" data-target="#mymodal4">
                    <p class="title">D.M.Viz</p>
                    <h3 class="title2">Click the banner for more details<h3>
                      <%= image_tag("dmv2.jpeg", class: "img-responsive", style: "height: 300px; max-width: 350px") %> 
                  </div>
                </div>
              </div>
            </div>
            <div class="face rear" style="background-color: white; opacity: 0.8">
            </div>      
          </div>
        </div>
      </div>  
    </div>  
    <div class="row hidden-xs" style="margin-bottom: 60px; margin-top: 60px; z-index: 10000">
      <div class="col-md-6 col-xs-12 col-sm-12 text-center" style="padding-top:30px">
        <a href="<%= pages_about_path %>"><%= image_tag("arrow_left.png", size: "400x80") %></a>
      </div> 
      <div class="col-md-6 col-xs-12 col-sm-12 text-center" style="padding-top:30px"> 
        <a href="<%= pages_skills_path %>"><%= image_tag("arrow_right.png", size: "400x80") %></a>
      </div>
    </div>  
    <div class="row hidden-md hidden-lg hidden-sm" style="margin-bottom: 60px; margin-top: 50px; z-index: 10000">
      <div class="col-md-6 col-xs-12 col-sm-12 text-center" style="padding-top:0px">
        <a href="<%= pages_about_path %>"><%= image_tag("arrow_left.png", size: "300x80") %></a>
      </div> 
      <div class="col-md-6 col-xs-12 col-sm-12 text-center" style="padding-top:0px"> 
        <a href="<%= pages_skills_path %>"><%= image_tag("arrow_right.png", size: "300x80") %></a>
      </div>
    </div>                     
  </div>          
</div>


<div class="modal font2" id="mymodal1">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">SportsApp</h2>
      </div>
      <div class="modal-body">
        <h5 style="font-weight: bold"><a href="#">App Platform Dependent Sharing App</a><br> 
        Inspired by a start up company from Santa Monica that provides a sports meeting service. IOS and Android users share a link with their friends for sports events and through my web app they are being transferred according to their device O.S using the Browser GEM to either a page that offers to download the compatible App online or in case of viewing through a computer, transferred to a web designed page that generates the shared event for more details. The app is currently deployed using Heroku. The app utilizes the HTTPParty GEM and header Authentication to extract user and event stored data from the company’s RESTful JSON API.</h5>
        <h5 style="font-weight: bold"><a href="http://wearecatchapp.herokuapp.com">Full Functionality Web App</a><br> 
        Inspired by a start up company from Santa Monica. A full Rails 5 web app. The app includes several features like: Authentication using Devise gem, modifying user profiles, adding preferred sports activities, creating, commenting and liking events, full friendship mechanism and an ActiveAdmin to handle administrator control. The app uses AWS S3 bucket to store uploaded photos and is deployed using Heroku. The app utilizes geocoder and Gmaps4rails GEMs to present events on a map.</h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal" style="font-size: 150%; padding: 6px 50px">Close</button>
        <a href="http://wearecatchapp.herokuapp.com", class="btn btn-primary" style="font-size: 150%; padding: 6px 50px" >View App</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal font2" id="mymodal2">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">Social Network</h2>
      </div>
      <div class="modal-body">
        <h4>Connect with friends, view profiles, post and share your thoughts!</h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal" style="font-size: 150%; padding: 6px 30px">Close</button>
        <a href="http://socialnet1.herokuapp.com/", class="btn btn-primary" style="font-size: 150%; padding: 6px 30px">View Social Network</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal font2" id="mymodal3">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">CarList</h2>
      </div>
      <div class="modal-body">
        <h4>View cars, compare specs and search our inventory!</h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal" style="font-size: 150%; padding: 6px 30px">Close</button>
        <a href="http://carlist.herokuapp.com/", class="btn btn-primary" style="font-size: 150%; padding: 6px 30px">View CarList</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal font2" id="mymodal4">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title">DMViz</h2>
      </div>
      <div class="modal-body">
        <h4>Check Your Knowledge of the CA traffic law with this interactive React.JS quiz</h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal" style="font-size: 150%; padding: 6px 30px">Close</button>
        <a href="http://dmv-quiz.herokuapp.com/", class="btn btn-primary" style="font-size: 150%; padding: 6px 30px">View DMViz</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/pages/skills.html.erb
<div class="container" style="margin-top: 5%">
  <div class="row">
    <div class="col-md-12">
      <section class="main">
        <div id="sb-container" class="sb-container">
          <div>
            <span class="sb-icon icon-cog"></span>
            <h4><span>Always Working On More Skills</span></h4>
          </div>
          <div>
            <span class="sb-icon icon-flight"></span>
            <h4><span>React.JS</span></h4>
            <%= image_tag("react-icon.png", size: "60x60") %>
          </div>  
          <div>
            <span class="sb-icon icon-eye"></span>
            <h4><span>AWS</span></h4>
            <%= image_tag("aws-icon.png", size: "60x60") %>
          </div>  
          <div>
            <span class="sb-icon icon-install"></span>
            <h4><span>Heroku</span></h4>
            <%= image_tag("heroku-icon.jpg", size: "60x60") %>
          </div>  
          <div>
            <span class="sb-icon icon-bag"></span>
            <h4><span>JavaScript</span></h4>
            <%= image_tag("javascript-icon.png", size: "60x60") %>
          </div>  
          <div>
            <span class="sb-icon icon-globe"></span>
            <h4><span>CSS3</span></h4>
            <%= image_tag("css3-icon.jpeg", size: "60x60") %>
          </div>  
          <div>
            <span class="sb-icon icon-picture"></span>
            <h4><span>Ruby on Rails</span></h4>
            <%= image_tag("rubyonrails-icon.png", size: "60x60") %>                     
          </div>  
          <div>
            <span class="sb-icon icon-video"></span>
            <h4><span>SQL</span></h4>
            <%= image_tag("SQL-icon.png", size: "60x60") %>                     
          </div>  
          <div>
            <span class="sb-icon icon-download"></span>
            <h4><span>HTML5</span></h4>
            <%= image_tag("HTML5-icon.png", size: "60x60") %>                      
          </div>
          <div>
            <span class="sb-icon icon-mobile"></span>
            <h4><span>Git</span></h4>
            <%= image_tag("github-icon.png", size: "60x60") %>                      
          </div>
          <div>
            <span class="sb-icon icon-camera"></span>
            <h4><span>Ruby</span></h4>
            <%= image_tag("ruby-icon.png", size: "60x60") %>                     
          </div>            
          <div>
            <h4><span>My Set Of Skills</span></h4>
            <span class="sb-toggle">Click to open / close</span>
            <h5><span style="margin-top: 30px">Skills</span></h5>                     
          </div>
        </div><!-- sb-container --> 
      </section>
    </div>
  </div>
</div>


<div class="row hidden-md hidden-lg" style="padding-bottom: 60px; padding-top: 50px; z-index: 10000">
  <div class="col-md-12 col-xs-12 col-sm-12 text-center">
    <a href="<%= pages_portfolio_path %>"><%= image_tag("arrow_left.png", size: "300x80") %></a>
    <a href="<%= pages_contact_path %>"><%= image_tag("arrow_right.png", size: "300x80") %></a>
  </div>
</div>  
<div class="row hidden-xs hidden-sm" style="padding-top: 50px; z-index: 10000">
  <div class="col-md-12 col-xs-12 col-sm-12 text-center">
    <a href="<%= pages_portfolio_path %>"><%= image_tag("arrow_left.png", size: "400x80") %></a>
    <a href="<%= pages_contact_path %>"><%= image_tag("arrow_right.png", size: "400x80") %></a>
  </div>
</div>

<script type="text/javascript">
$(function() {
  $( '#sb-container' ).swatchbook( {
          // number of degrees that is between each item
          angleInc : 15,
          neighbor : 15,
          // if it should be closed by default
          initclosed : true,
          // index of the element that when clicked, triggers the open/close function
          // by default there is no such element
          closeIdx : 11
        } );
});
</script>